accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('follow/<str:username>/', views.follow, name="follow"),
]

crud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('<int:post_pk>/delete/', views.delete, name='delete'),
    path('<int:post_pk>/update/', views.update, name='update'),
    path('<int:post_pk>/answer/<str:answer>/', views.answer, name='answer'),
    path('<int:post_pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:post_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:post_pk>/likes/', views.likes, name='likes'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')

posts/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=80)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')

    select1_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='select1_post')
    select1_content = models.TextField()
    img1 = models.ImageField(blank=True, upload_to='images1/')
    img1_thumbnail = ImageSpecField(source='img1',
        processors=[ResizeToFill(300, 300)],
        format='JPEG',
        options={'quality': 100})
    
    select2_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='select2_post')
    select2_content = models.TextField()
    img2 = models.ImageField(blank=True, upload_to='images2/')
    img2_thumbnail = ImageSpecField(source='img2',
        processors=[ResizeToFill(300, 300)],
        format='JPEG',
        options={'quality': 100})



class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)    

# class PostImage(models.Model):
#     post = models.ForeignKey(Post, on_delete=models.CASCADE)
#     img1 = models.ImageField(blank=True, upload_to='images1/')
#     img2 = models.ImageField(blank=True, upload_to='images2/')

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm, PasswordChangeForm, UsernameField
from django.contrib.auth import get_user_model
from django import forms

class CustomUserCreationForm(UserCreationForm):
    username = UsernameField(
         label='ID', 
         label_suffix='', 
         widget=forms.TextInput(
                attrs={
                    'class': 'form-control custom-signup-form-field', 
                }
            )
        )
    email = forms.EmailField(
        label='이메일',
        label_suffix='',
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control custom-signup-form-field'}))
    password1 = forms.CharField(
        label='비밀번호', 
        label_suffix='', 
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control custom-signup-form-field'}))
    password2 = forms.CharField(
        label='비밀번호 확인', 
        label_suffix='', 
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control custom-signup-form-field'}))
    
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = (
            'username',
            'email',
            'password1',
            'password2',
        )

class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = (
            'email',
        )
    
    email = forms.EmailField(label='이메일', label_suffix='', widget=forms.EmailInput(
        attrs={'class': 'form-control', 'style': 'width: 250px;'}))
    # password = None


class CustomAuthenticationForm(AuthenticationForm):
    username = UsernameField(
        label='',
        widget=forms.TextInput(
            attrs={
                    'class': 'form-control',
                    'autofocus': True,
                    'placeholder':"username",
                    'style': 'width: 200px',
                }
            )
        )
    password = forms.CharField(
        label='',
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                    'class': 'form-control',
                    'autocomplete': 'current-password',
                    'placeholder': "password",
                    'style': 'width: 200px',
                }
            ),
        )

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomUserChangeForm, CustomAuthenticationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

# Create your views here.
def signup(request):
    if request.user.is_authenticated:
        return redirect('posts:index')
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('posts:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


def login(request):
    if request.user.is_authenticated:
        return redirect('posts:index')
    
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('posts:index')
    else:
        form = CustomAuthenticationForm()

    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@login_required
def logout(request):
    auth_logout(request)
    return redirect('posts:index')


def profile(request, username):
    person = get_user_model().objects.get(username = username)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)

# path('follow/<str:username>', views.follow, name="follow"),
def follow(request, username):
    you = get_user_model().objects.get(username = username)
    me = request.user
    if you != me:
        if me in you.followers.all():
            you.followers.remove(me)
            is_followed = False
        else:
            you.followers.add(me)
            is_followed = True
        context = {
            'is_followed': is_followed,
            'followings_count': you.followings.count(),
            'followers_count': you.followers.count(),
        }
        return JsonResponse(context)
    return redirect('accounts:profile', you.username)

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-4"></div>
    <div id="custom-box-wrapper" class="col-4">
      <div id="custom-box" class="d-flex flex-column">
        <div class="row my-3 text-center wordwrap">
          <h1>밸런스 게임</h1>
        </div>
        <div class="row my-3">
          <form action="{% url 'accounts:login' %}" method="POST">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" class="btn form-control custom-btn" value="로그인">
          </form>
        </div>
        <div class="row my-3 text-center">
          <p class="custom-text-small">아직도 회원이 아니신가요? 지금바로 <a href="{% url 'accounts:signup' %}">회원가입</a>.</p>
        </div>
        <div class="row my-3 custom-box d-flex flex-row justify-content-center">
        </div>
      </div>
    </div>
      <div class="col-4"></div>
  </div>
</div>




<style>
.custom-text-small{
  font-size:0.6rem;
}
.custom-btn{
  background-color : lightgray;
  width: 100%;
}
#custom-box-wrapper{
  width: auto;
  border: 1px solid lightgray;
  border-radius: 5px;
}
#custom-box{
  padding: 20px;
  word-break: keep-all;
  justify-content: center;
}
</style>

{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
  <div class="d-flex ">
    <div>
      <h1>{{ person.username }}의 프로필 입니다.</h1>
    </div>
    <div class="ms-5 align-self-center">
      {% if person != user %}
      <form id="follow-form" data-user-id="{{ person.username }}">
        {% csrf_token %}
        {% if user in person.followers.all %}
          <input class="btn btn-outline-primary" type="submit" value="팔로우 취소">
        {% else %}
          <input class="btn btn-outline-primary" type="submit" value="팔로우">
        {% endif %}
      </form>
      {% endif %}
    </div>
  </div>


  <!-- 팔로워 모달 버튼 -->
  <div class="mt-3">
    <button type="button" class="btn btn-primary me-3" data-bs-toggle="modal" data-bs-target="#followersModal">
      <span id="followers-count">{{ person.followers.all|length }}</span> 팔로워
    </button>

    <!-- 팔로잉 모달 버튼 -->
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#followingsModal">
      <span id = 'followings-count'>{{ person.followings.all|length }}</span> 팔로잉 
    </button>
  </div>

  <!-- 팔로워 Modal -->
  <div class="modal fade" id="followersModal" tabindex="-1" aria-labelledby="followersModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="followersModalLabel">팔로워</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          {% for follower in person.followers.all %}
            <span><a class="text-decoration-none link-secondary fw-bold" href="{% url 'accounts:profile' follower.username %}"><i class="bi bi-people-fill me-1"></i>{{ follower }}</a></span>
          {% endfor %}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

  <!-- 팔로잉 Modal -->
  <div class="modal fade" id="followingsModal" tabindex="-1" aria-labelledby="followingsModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="followingsModalLabel">팔로잉</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          {% for following in person.followings.all %}
            <span><a class="text-decoration-none link-secondary fw-bold" href="{% url 'accounts:profile' following.username %}"><i class="bi bi-people-fill me-1"></i>{{ following }}</a></span>
          {% endfor %}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  
  <hr>

  <h1><i class="bi bi-hand-thumbs-up"></i> 좋아요 목록 </h1>
  <br>
  {% for post in person.post_set.all %}
    <p>{{ person.username }}님은 {{ post.select1_content }}를(을) 좋아합니다.</p>
  {% endfor %}

  <hr>
  
  <h1><i class="bi bi-postcard"></i> 게시글 목록 </h1>
  <br>
  {% for post in person.post_set.all %}
  <p><a class="text-decoration-none" href="{% url 'posts:detail' post.pk %}">{{ post.title }}</a></p>
  {% endfor %}
  
  <hr>
  
  <h1><i class="bi bi-chat-left-dots"></i> 댓글 목록 </h1>
  {% for comment in person.comment_set.all %}
  <p><a class="text-decoration-none" href="{% url 'posts:detail' comment.post.pk %}">{{ comment.content }}</a></p>
  {% endfor %}
    
{% endblock content %}


{% block script %}
<script>
  const form = document.querySelector('#follow-form')
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
  form.addEventListener('submit', function(event) {
    event.preventDefault()
    const userId = event.target.dataset.userId
    
    axios({
      method: 'post',
      url: `/accounts/follow/${userId}/`,
      headers: {'X-CSRFToken': csrftoken},
    })
      .then((response) => {
        const isFollowed = response.data.is_followed
        const followBtn = document.querySelector('#follow-form > input[type=submit]')
        if (isFollowed === true) {
          followBtn.value = '팔로우 취소'
        } else {
          followBtn.value = '팔로우'
        }
        const followingsCounterTag = document.querySelector('#followings-count')
        const followersCounterTag = document.querySelector('#followers-count')
        const followingsCountData = response.data.followings_count
        const followersCountData = response.data.followers_count
        followingsCounterTag.textContent = followingsCountData
        followersCounterTag.textContent = followersCountData
      })
  })
  
</script>
{% endblock script %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-3"></div>
    <div id="custom_box_wrapper" class="col-6">
      <div id="custom_box" class="d-flex flex-column">
        <div class="row my-3 text-center">
          <h1>밸런스 게임의 세계로</h1>
        </div>
          <form action="{% url 'accounts:signup' %}" method="POST" id="signup-form">
          {% csrf_token %}
            {% for field in form %}
            <div class="row my-3 px-5">
              <label for="{{ field.id }}"><span class="custom-label">{{ field.label }}</label>
              {{ field }}
            </div>
            {% endfor %}
            <div class="row my-5 px-5">
            <input type="submit" class="btn form-control custom_btn" value="회원가입">
            </div>
          </form>
        
        <div class="row my-3">
          
        </div>
        <div class="row my-3">
          
        </div>
      </div>
    </div>
    <div class="col-3">

      </div>
    </div>
  </div>

<style>
  .custom-signup-form-field{
  }
  .custom-label{
    color: gray;
    font-size:0.8rem;
  }
  .custom_btn{
    background-color : lightgray;
  }
  
  #signup-form{
  }
  #custom_box_wrapper{
    width: 50%;
    border: 1px solid lightgray;
    border-radius: 5px;
  }
  #custom_box{
    padding: 20px;
    word-break: keep-all;
    justify-content: center;
  }
</style>


{% endblock content %}