accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('follow/<str:username>/', views.follow, name="follow"),
]

crud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('<int:post_pk>/delete/', views.delete, name='delete'),
    path('<int:post_pk>/update/', views.update, name='update'),
    path('<int:post_pk>/answer/<str:answer>/', views.answer, name='answer'),
    path('<int:post_pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:post_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:post_pk>/likes/', views.likes, name='likes'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Balence Game</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
    <style>
      {% block style %}
      {% endblock style %}
    </style>
  </head>
  <body>
    {% include 'nav.html' %}
    <div class="container" style="padding: 7rem 0;">
      {% block content %}
      {% endblock content %}
    </div>
    {% include 'footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
      {% block script %}
      {% endblock script %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
</html>

templates/footer.html
{% load static %}
<footer class="bottom-0 w-100">
  {% comment %} <div class="container">
    <div class="row"> {% endcomment %}
  <div class="col-8 card border-0 me-5" style="max-width: 800px;">
    <div class="row g-0">
      <div class="col-md-2 d-flex justify-content-center align-items-center">
        <img id="dev-logo" src="{% static 'dev.png' %}" alt="개발자" class="img-fluid rounded-start">
      </div>
      <div class="col-md-10">
        <div class="card-body">
          <div class="accordion accordion-flush col" id="accordionFlushExample">
            <div class="accordion-item">
              <h2 class="accordion-header">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                  이수정
                </button>
              </h2>
              <div id="flush-collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
                <div class="accordion-body row">
                  <div class="col-4">
                    <img class="img-fluid" src="{% static 'sjsj.png' %}" alt="">
                  </div>
                  <div class="col-8">
                    <h3>이수정</h3>
                    <hr>
                    <p>금요일 조아!</p>
                    <p><a href="https://github.com/Shureeshu/"><img id="github-logo" src="{% static 'github.png' %}" alt="깃헙"></a></p>
                  </div>
                </div>
              </div>
            </div>
            <div class="accordion-item">
              <h2 class="accordion-header">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
                  장민지
                </button>
              </h2>
              <div id="flush-collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
                <div class="accordion-body row">
                  <div class="col-4">
                    <img class="img-fluid" src="{% static 'mg.jpg' %}" alt="">
                  </div>
                  <div class="col-8">
                    <h3>장민지</h3>
                    <hr>
                    <p>모두들 수고 많으셨습니다~! 많이 배워갑니당 ^__^</p>
                    <p><a href="https://github.com/mungjimangji"><img id="github-logo" src="{% static 'github.png' %}" alt="깃헙"></a></p>
                  </div>
                </div>
              </div>
            </div>
            <div class="accordion-item">
              <h2 class="accordion-header">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
                  최은비
                </button>
              </h2>
              <div id="flush-collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
                <div class="accordion-body row">
                  <div class="col-4">
                    <img class="img-fluid" src="{% static 'eunbi.jpg' %}" alt="">
                  </div>
                  <div class="col-8">
                    <h3>최은비</h3>
                    <hr>
                    <p>3일동안 재밌었습니다 ㅎㅎ 프로젝트에서 다시 만났으면 좋겠어요</p>
                    <p><a href="https://github.com/rloldl-c"><img id="github-logo" src="{% static 'github.png' %}" alt="깃헙"></a></p>
                  </div>
                </div>
              </div>
            </div>
            <div class="accordion-item">
              <h2 class="accordion-header">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseFour" aria-expanded="false" aria-controls="flush-collapseTwo">
                  장하늬
                </button>
              </h2>
              <div id="flush-collapseFour" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
                <div class="accordion-body row">
                  <div class="col-4">
                    <img class="img-fluid" src="{% static 'hany.png' %}" alt="">
                  </div>
                  <div class="col-8">
                    <h3>장하늬</h3>
                    <hr>
                    <p>살려줘....</p>
                    <p><a href="https://github.com/hany0147"><img id="github-logo" src="{% static 'github.png' %}" alt="깃헙"></a></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-2 d-flex justify-content-between align-items-center ms-5">
    <p><a class="link-secondary text-decoration-none" href="#">고객센터</a></p>
    <p><a class="link-secondary text-decoration-none" href="#">이용약관</a></p>
    <p><a class="link-secondary text-decoration-none" href="#">문의하기</a></p>
  </div>
</footer>

templates/nav.html
{% load static %}

<nav class="fixed-top navbar navbar-expand-lg bg-body-tertiary">
  <div class="container">
    <a class="navbar-brand fw-bold" href="{% url 'posts:index' %}">
      <img id="logo" src="{% static 'logo.png' %}" alt="로고">
      Balance Game
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'posts:create' %}">만들기</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">랭킹</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            태그
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">음식</a></li>
            <li><a class="dropdown-item" href="#">생존</a></li>
            <li><a class="dropdown-item" href="#">상황</a></li>
          </ul>
        </li>
      </ul>
      <div class="d-flex">
        {% if request.user.is_authenticated %}
          <a class="btn fw-bold text-black" href="{% url 'accounts:profile' user.username %}">{{ user }}님</a>
          <form action="{% url 'accounts:logout' %}" method="POST">
            {% csrf_token %}
            <input class="form-control me-2 btn btn-outline-danger" type="submit" value="로그아웃">
          </form>
          {% else %}
            <a class="btn btn-outline-primary me-2" href="{% url 'accounts:signup' %}">회원가입</a>
            <a class="btn btn-outline-success" href="{% url 'accounts:login' %}">로그인</a>
          {% endif %}
      </div>
    </div>
  </div>
</nav>