accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('follow/<str:username>/', views.follow, name="follow"),
]

crud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('<int:post_pk>/delete/', views.delete, name='delete'),
    path('<int:post_pk>/update/', views.update, name='update'),
    path('<int:post_pk>/answer/<str:answer>/', views.answer, name='answer'),
    path('<int:post_pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:post_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:post_pk>/likes/', views.likes, name='likes'),
]

posts/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=80)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')

    select1_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='select1_post')
    select1_content = models.TextField()
    img1 = models.ImageField(blank=True, upload_to='images1/')
    img1_thumbnail = ImageSpecField(source='img1',
        processors=[ResizeToFill(300, 300)],
        format='JPEG',
        options={'quality': 100})
    
    select2_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='select2_post')
    select2_content = models.TextField()
    img2 = models.ImageField(blank=True, upload_to='images2/')
    img2_thumbnail = ImageSpecField(source='img2',
        processors=[ResizeToFill(300, 300)],
        format='JPEG',
        options={'quality': 100})



class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)    

# class PostImage(models.Model):
#     post = models.ForeignKey(Post, on_delete=models.CASCADE)
#     img1 = models.ImageField(blank=True, upload_to='images1/')
#     img2 = models.ImageField(blank=True, upload_to='images2/')

posts/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    title = forms.CharField(
         label='', 
         label_suffix='', 
         widget=forms.TextInput(
                attrs={
                    'class': 'form-control', 
                    'autofocus': True,
                    'placeholder':"상황 설명(필수)",
                }
            )
        )
    select1_content = forms.CharField(
         label='', 
         label_suffix='', 
         widget=forms.Textarea(
                attrs={
                    'class': 'form-control text-wrap custom-select-form', 
                    'autofocus': True,
                    'placeholder':"선택지1(필수)",
                }
            )
        )
    select2_content = forms.CharField(
         label='', 
         label_suffix='', 
         widget=forms.Textarea(
                attrs={
                    'class': 'form-control text-wrap custom-select-form', 
                    'autofocus': True,
                    'placeholder':"선택지2(필수)",
                }
            )
        )
    img1 = forms.ImageField(
        label='', 
        label_suffix='',
        required=False,
        )
    img2 = forms.ImageField(
        label='', 
        label_suffix='',
        required=False,
        )
    class Meta:
        model = Post
        fields = ('title', 'select1_content', 'select2_content', 'img1', 'img2',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
    
    content = forms.CharField(
        label='댓글',
        label_suffix='',
        widget=forms.Textarea(
            attrs={
                'placeholder': '댓글을 작성주세요.',
                "class": "form-control",
                'style': 'width: 100%; height: 3rem;',   
            }
        ),
    )

posts/views.py
from django.shortcuts import render, redirect
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.core.paginator import Paginator

# Create your views here.
def index(request):
    posts = Post.objects.order_by('-pk')
    page = request.GET.get('page', '1')
    per_page = 5
    paginator = Paginator(posts, per_page)
    page_obj = paginator.get_page(page)
    last = paginator.num_pages
    context = {
        'posts': page_obj,
        'last' : last,
    }
    return render(request, 'posts/index.html', context)


@login_required
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:detail', post.pk)

    else:
        form = PostForm()

    context = {
        'form': form,
    }
    return render(request, 'posts/create.html', context)



def detail(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    last = Post.objects.last()
    comment_form = CommentForm()
    comments = post.comment_set.all()
    context = {
        'post': post,
        'last': last,
        'comment_form': comment_form,
        'comments': comments,
    }
    return render(request, 'posts/detail.html', context)

def delete(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    if request.user == post.user:
        post.delete()
    return redirect('posts:index')

def update(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    if request.user == post.user:
        if request.method == "POST":
            form = PostForm(request.POST, request.FILES, instance=post)
            if form.is_valid():
                form.save()
                return redirect('posts:detail', post.pk)
        else:
            form = PostForm(instance=post)
    else:
        return redirect('posts:index')
    context = {
        'post' : post,
        'form' : form,
    }
    return render(request, 'posts/update.html', context)




@login_required
def answer(request, post_pk, answer):
    # POST posts/<int:post_pk>/answer/<str:answer>/
    post = Post.objects.get(pk=post_pk)
    user = request.user
    if request.method == "POST":
        if user in post.select1_users.all() or user in post.select2_users.all():
            pass
        else:
            if answer == post.select1_content:
                post.select1_users.add(user)
                is_select = True
                context = {
                    'is_select' : is_select,
                    'select1_count': post.select1_users.count()
                }
                
            elif answer == post.select2_content:
                post.select2_users.add(user)
                is_select = True
                context = {
                    'is_select' : is_select,
                    'select2_count': post.select2_users.count()
                }
            return JsonResponse(context)
    return redirect('posts:detail', post_pk, context)


@login_required
def comment_create(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    comment_form = CommentForm(request.POST)

    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.user = request.user
        comment.post = post
        comment.save()

        return redirect('posts:detail', post.pk)

    context = {
        'post': post,
        'comment_form' : comment_form,
    }
    return render(request, 'posts/detail.html', context)


@login_required
def comment_delete(request, post_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    
    if request.user == comment.user:
        # 댓글 삭제
        comment.delete()
    return redirect('posts:detail', post_pk)


def likes(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    if request.user in post.like_users.all():
        post.like_users.remove(request.user)
        is_liked = False
    else:
        post.like_users.add(request.user)
        is_liked = True
    context = {
        'is_liked': is_liked,
        'likes_count': post.like_users.count()
    }
    return JsonResponse(context)
    

posts/templates/posts/create.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
  a {
    text-decoration: none;
    color: black;
  }

  .image-wrap {
    margin: 0.5rem;
  }

  .image {
    width: 100%;
  }

  #select1, #select2 {
    width: calc(100% - 1.5rem);
    height: 8rem;
    margin: 0.5rem;
  }

  p {
    margin: 0;
  }

  .comment-user {
    font-size: 0.875rem;
    font-weight: bold;
  }

  .comment-date {
    color: #606060;
    font-size: 0.75rem;
  }

  .btn-remove {
    text-decoration: none;
    padding: 0;
    font-size: 0.875rem;
    color: #dc3545;
    font-weight: bold;
  }

  .custom-select-form {
    background-color: lightgray;
    height: 50%;
  }
{% endblock style %}

{% block content %}
<div class="container p-5">
  <h1>새로운 게임</h1>
  <form action="{% url 'posts:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row my-3">
      <div class="col">{{ form.title }}</div>
    </div>
    <div class="row my-3 g-1">
      <div class="col d-flex flex-column">
        {{ form.select1_content }}
        {{ form.img1 }}
      </div>
      <div class="col d-flex flex-column">
        {{ form.select2_content }}
        {{ form.img2 }}
      </div>
    </div>
    <input type="submit" class="btn btn-outline-success" value="완료">
  </form>
</div>
{% endblock content %}

posts/templates/posts/detail.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
  a {
    text-decoration: none;
    color: black;
  }

  .image-wrap {
    margin: 0.5rem;
  }

  .image {
    width: 100%;
  }

  #select1, #select2 {
    width: calc(100% - 1.5rem);
    height: 8rem;
    margin: 0.5rem;
  }

  p {
    margin: 0;
  }

  .dropdown-toggle::after {
    display: none;
  }

  .dropdown-item.active, .dropdown-item:active {
    background-color: rgba(0, 0, 0, 0.075);
  }

  .comment-user {
    font-size: 0.875rem;
    font-weight: bold;
  }

  .comment-date {
    color: #606060;
    font-size: 0.75rem;
  }

  .btn-remove {
    text-decoration: none;
    padding: 0;
    font-size: 0.875rem;
    color: #dc3545;
    font-weight: bold;
  }
{% endblock style %}

{% block content %}
  {% comment %} <p>번호 - {{ post.pk }}</p> {% endcomment %}
  <div class="d-flex align-items-center mb-3 gap-2">
    <a href="{% url 'posts:index' %}" class="text-secondary">
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
      <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
      </svg>
    </a>
    <h3 class="fw-bold m-0">{{ post.title }}</h3>
  </div>
  <div class="d-flex justify-content-between px-3 align-items-center">
    <a href="{% url 'accounts:profile' post.user %}">{{ post.user }}</a>
    <div class="d-flex gap-2 align-items-center">
      {% if request.user.is_authenticated %}
        <form id="likes-form" data-post-id="{{ post.pk }}">
          {% csrf_token %}
          {% if request.user in post.like_users.all %}
            <button type="submit" class="btn btn-primary">
              <i class="bi bi-heart-fill"></i>
              <span id="likes-count" class="fw-bold">{{ post.like_users.all|length }}</span>
            </button>
          {% else %}
            <button type="submit" class="btn btn-outline-primary">
              <i class="bi bi-heart"></i>
              <span id="likes-count" class="fw-bold">{{ post.like_users.all|length }}</span>
            </button>
          {% endif %}
        </form>
      {% else %}
        <button type="submit" class="btn btn-primary" disabled>
          <i class="bi bi-hand-thumbs-up-fill"></i>
        </button>
      {% endif %}
      {% if post.user == user %}
        <div class="dropdown">
          <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-three-dots-vertical"></i>
          </button>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'posts:update' post.pk %}">수정하기</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item text-danger" href="{% url 'posts:delete' post.pk %}">삭제하기</a></li>
          </ul>
        </div>
      {% endif %}
    </div>
  </div>
  <hr>
  <div class="d-flex gap-3">
    <div class="d-flex flex-column gap-3 w-100">
      <form id="select-form1" data-post-id="{{ post.pk }}" data-post-content="{{ post.select1_content }}" data-select-count="{{ post.select1_users.count }}">
        {% csrf_token %}
        {% if user in post.select1_users.all %}
          <input id="select1" type="submit" value="{{ post.select1_content }} - {{ post.select1_users.count }}" class="btn btn-light fw-bold fs-4" style="background-color: #d3d4d5;">
        {% else %}
          <input id="select1" type="submit" value="{{ post.select1_content }} - {{ post.select1_users.count }}" class="btn btn-light fw-bold fs-4">
        {% endif %}
      </form>
      <div class="image-wrap overflow-hidden">
        {% if post.img1 %}
        <img src="{{ post.img1_thumbnail.url }}" alt="" class="image">
        {% else %}
        <img src="{% static '1.png' %}" alt="" class="image">
        {% endif %}
      </div>
    </div>
    

    <div class="d-flex flex-column gap-3 w-100">
      <form id="select-form2" data-post-id="{{ post.pk }}" data-post-content="{{ post.select2_content }}" data-select-count="{{ post.select2_users.count }}">
        {% csrf_token %}
        {% if user in post.select2_users.all %}
          <input id="select2" type="submit" value="{{ post.select2_content }} - {{ post.select2_users.count }}" class="btn btn-light fw-bold fs-4" style="background-color: #d3d4d5;">
        {% else %}
          <input id="select2" type="submit" value="{{ post.select2_content }} - {{ post.select2_users.count }}" class="btn btn-light fw-bold fs-4">
        {% endif %}
          
      </form>
      <div class="image-wrap overflow-hidden">
        {% if post.img2 %}
          <img src="{{ post.img2_thumbnail.url }}" alt="" class="image">
        {% else %}
          <img src="{% static '2.png' %}" alt="" class="image">
        {% endif %}
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-between my-4">
    {% if post.pk == 1 %}
      <a href="" class="btn btn-outline-dark disabled">이전 질문</a>
    {% else %}
      <a href="{% url 'posts:detail' post.pk|add:-1 %}" class="btn btn-outline-dark">이전 질문</a>
    {% endif %}
    {% if post.pk == last.pk %}
      <a href="{% url 'posts:detail' post.pk|add:+1 %}" class="btn btn-outline-dark disabled">다음 질문</a>
    {% else %}  
      <a href="{% url 'posts:detail' post.pk|add:+1 %}" class="btn btn-outline-dark">다음 질문</a>
    {% endif %}
  </div>
  
  <p>댓글({{ post.comment_set.all|length }})</p>
  <form action="{% url 'posts:comment_create' post.pk %}" method="POST" class="d-flex justify-content-between gap-3 my-3  ">
    {% csrf_token %}
    {% for field in comment_form %}
    <div class="w-100">{{ field }}</div>
    {% endfor %}
    {% comment %} {{ comment_form.as_p }} {% endcomment %}
    <input type="submit" value="작성" class="btn btn-outline-success">
  </form>
  <hr>
  {% for comment in comments %}
    <div class="d-flex justify-content-between">
      <div class="d-flex flex-column gap-1">
        <a href="{% url 'accounts:profile' comment.user %}" class="comment-user">{{ comment.user }}</a>
        <p class="comment-content">{{ comment.content }}</p>
        <p class="comment-date">{{ comment.created_at }}</p>
      </div>
      {% if comment.user == user %}
        <form action="{% url 'posts:comment_delete' post.pk comment.pk %}" method="POST" class="align-self-end">
          {% csrf_token %}
          <input type="submit" value="삭제" class="btn btn-link btn-remove">
        </form>
      {% endif %}
    </div>
    <hr>
  {% endfor %}
{% endblock content %}

{% block script %}
  <script>
    const form = document.querySelector('#likes-form')
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
    form.addEventListener('submit', function (event) {
      event.preventDefault()
      const postId = event.target.dataset.postId
      axios({
        method: 'post',
        url: `/posts/${postId}/likes/`,
        headers: {'X-CSRFToken': csrftoken},
      })
        .then((response) => {
          const isLiked = response.data.is_liked
          const likeBtn = document.querySelector('#likes-form > button[type=submit]')
          const likeIcon = document.querySelector('#likes-form > button[type=submit] > i')
          if (isLiked === true) {
            likeBtn.classList.remove("btn-outline-primary")
            likeBtn.classList.add("btn-primary")
            likeIcon.classList.remove("bi-heart")
            likeIcon.classList.add("bi-heart-fill")
            likeBtn.value = '좋아요 취소'
          } else {
            likeBtn.classList.remove("btn-primary")
            likeBtn.classList.add("btn-outline-primary")
            likeIcon.classList.remove("bi-heart-fill")
            likeIcon.classList.add("bi-heart")
            likeBtn.value = '좋아요'
          }
          const likesCountTag = document.querySelector('#likes-count')
          const likesCountData = response.data.likes_count
          likesCountTag.textContent = likesCountData
        })

    })
 
    const form1 = document.querySelector('#select-form1')
    const form2 = document.querySelector('#select-form2')
    
    form1.addEventListener('submit', function (event) {
      event.preventDefault()
      const postId = event.target.dataset.postId
      const postContent = event.target.dataset.postContent
      
      axios({
        method: 'post',
        url: `/posts/${postId}/answer/${postContent}/`,
        headers: {'X-CSRFToken': csrftoken},
      })
      .then((response) => {
        console.log(response)
        const isSelect = response.data.is_select
        const selectBtn = document.querySelector('#select1')
        const selectCountData = response.data.select1_count
        if (isSelect === true) {
          selectBtn.style.backgroundColor = '#d3d4d5'
          selectBtn.value = `${postContent} - ${selectCountData}`
        }
      })
    })

    form2.addEventListener('submit', function (event) {
      event.preventDefault()
      const postId = event.target.dataset.postId
      const postContent = event.target.dataset.postContent
      
      axios({
        method: 'post',
        url: `/posts/${postId}/answer/${postContent}/`,
        headers: {'X-CSRFToken': csrftoken},
      })
      .then((response) => {
        console.log(response)
        const isSelect = response.data.is_select
        const selectBtn = document.querySelector('#select2')
        const selectCountData = response.data.select2_count
        if (isSelect === true) {
          selectBtn.style.backgroundColor = '#d3d4d5'
          selectBtn.value = `${postContent} - ${selectCountData}`
        }
      })
    })
  </script>
{% endblock script %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block style %}
  li {
    list-style: none;
  }

  ul {
    padding: 0;
  }

  a {
    text-decoration: none;
    color: black;
  }

  .table>:not(caption)>*>* {
    padding: 1rem 0.5rem;
  }

  .post-num {
    font-size: 0.875rem;
  }

  .post-title {
    width: 45rem;
  }

{% endblock style %}

{% block content %}
  
  <a href="{% url 'posts:create' %}" class="btn btn-outline-secondary mb-3">생성하기</a>
  <table class="table table-hover text-center">
    <thead>
      <tr>
        <th scope="col">No.</th>
        <th scope="col">제목</th>
        <th scope="col">작성자</th>
        <th scope="col">추천</th>
        <th scope="col">댓글</th>
      </tr>
    </thead>
    <tbody>
      {% for post in posts %}
        <tr>
          <th scope="row" class="post-num">{{ post.pk }}</th>
          <td class="post-title"><a href="{% url 'posts:detail' post.pk %}">{{ post.title }}</a></td>
          <td><a href="{% url 'accounts:profile' post.user.username %}">{{ post.user }}</a></td>
          <td>
            {% if request.user in post.like_users.all %}
              ❤ {{ post.like_users.all|length }}
            {% else %}
              🤍 {{ post.like_users.all|length }}
            {% endif %}
          </td>
          <td>{{ post.comment_set.all|length }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  {% comment %} 페이지네이션 start! {% endcomment %}
  <ul class="pagination justify-content-center mt-5">

    {% if posts.number == 1 %}
      <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">《</a>
      </li>
    {% else %}
      <li class="page-item">
        <a class="page-link" href="?page=1">《</a>
      </li>
    
    {% endif %}
    
    {% if posts.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ posts.previous_page_number }}">〈</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">〈</a>
      </li>
    {% endif %}
    {% comment %} 페이지 번호 무한 생성 막는 조건문 (현재 페이지에서 +- 5) {% endcomment %}
    {% for page_number in posts.paginator.page_range %}
      {% if page_number >= posts.number|add:-5 and page_number <= posts.number|add:5 %}
        {% if page_number == posts.number %}
          <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
          </li>
        {% endif %}
      {% endif %}
    {% endfor %}
    
    {% if posts.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ posts.next_page_number }}">〉</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">〉</a>
      </li>
    {% endif %}

    {% if posts.number == last %}
      <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">》</a>
      </li>
    {% else %}
      <li class="page-item">
        <a class="page-link" href="?page={{ last }}">》</a>
      </li>
    
    {% endif %}

    
  </ul>



{% endblock content %}

posts/templates/posts/update.html
{% extends 'base.html' %}
{% block style %}
  a {
    text-decoration: none;
    color: black;
  }

  .image-wrap {
    margin: 0.5rem;
  }

  .image {
    width: 100%;
  }

  #select1, #select2 {
    width: calc(100% - 1.5rem);
    height: 8rem;
    margin: 0.5rem;
  }

  p {
    margin: 0;
  }

  .comment-user {
    font-size: 0.875rem;
    font-weight: bold;
  }

  .comment-date {
    color: #606060;
    font-size: 0.75rem;
  }

  .btn-remove {
    text-decoration: none;
    padding: 0;
    font-size: 0.875rem;
    color: #dc3545;
    font-weight: bold;
  }

  .custom-select-form {
    background-color: lightgray;
    height: 50%;
  }
{% endblock style %}
{% block content %}
<div class="container p-5">
  <h1>수정하기</h1>
  <form action="{% url 'posts:update' post.pk %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row my-3">
      <div class="col">{{ form.title }}</div>
    </div>
    <div class="row my-3 g-1">
      <div class="col d-flex flex-column">
        {{ form.select1_content }}
        {{ form.img1 }}
      </div>
      <div class="col">
        {{ form.select2_content }}
        {{ form.img2 }}
      </div>
    </div>
      <input type="submit" class="btn btn-outline-success" value="완료">
  </form>
</div>
{% endblock content %}